name: XNAP
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib==3.3.*
  - numpy==1.18.5
  - scipy #==1.9.3
  - scikit-learn #==0.23.*
  - pandas
  - protobuf==3.20
  - tqdm
  - typer
  - pip:
      - -e .
      - arrow==0.17.0
      - tensorflow==2.3.0
